/**
 * Lookup keys: lowercase, accents stripped. Glosses are short English equivalents for learners.
 * Used when a cue’s `words[].t` is a full sentence: we split on spaces and gloss each token.
 */
export const ES_LEARNER_LEXICON: Record<string, { en: string; pron?: string }> = {
  a: { en: "to; at" },
  abandonados: { en: "neglected" },
  acaba: { en: "just (has just)" },
  acabo: { en: "I have just" },
  afectuosa: { en: "affectionate (f.)", pron: "ah-fehk-TOO-oh-sah" },
  después: { en: "after; then" },
  ah: { en: "ah" },
  ahí: { en: "there" },
  ahora: { en: "now" },
  al: { en: "to the; a + el" },
  allí: { en: "there" },
  agradecimiento: { en: "gratitude" },
  anda: { en: "come on; go" },
  andar: { en: "to walk" },
  animalito: { en: "little animal" },
  años: { en: "years", pron: "AH-nyohs" },
  antes: { en: "before" },
  aparte: { en: "apart from; besides" },
  apacible: { en: "peaceful; quiet" },
  apenas: { en: "barely; hardly" },
  aquí: { en: "here" },
  arañas: { en: "spiders" },
  así: { en: "like this; so" },
  autocar: { en: "bus; coach" },
  aún: { en: "still; yet" },
  bien: { en: "well; good", pron: "byehn" },
  bienvenida: { en: "welcome (f.)" },
  baja: { en: "come down" },
  buena: { en: "good (f.)" },
  bueno: { en: "good" },
  buenos: { en: "good (pl.)" },
  campo: { en: "field; countryside" },
  campos: { en: "fields" },
  cariño: { en: "affection; dear", pron: "kah-REE-nyoh" },
  carta: { en: "letter" },
  casa: { en: "house; home" },
  casi: { en: "almost" },
  celda: { en: "cell (monk/nun)" },
  comba: { en: "jump rope" },
  como: { en: "how; like; as" },
  con: { en: "with" },
  convento: { en: "convent", pron: "kohn-BEHN-toh" },
  conozco: { en: "I know (a person)" },
  conseguirlo: { en: "to get it" },
  costó: { en: "it cost" },
  creerá: { en: "you will think" },
  criada: { en: "maid; servant (f.)" },
  cuándo: { en: "when?" },
  cuánto: { en: "how much" },
  cuando: { en: "when" },
  cómo: { en: "how?" },
  cuerda: { en: "rope" },
  días: { en: "days", pron: "DEE-ahs" },
  de: { en: "of; from" },
  debes: { en: "you must" },
  debo: { en: "I owe" },
  decir: { en: "to say" },
  del: { en: "of the" },
  demás: { en: "the rest" },
  demasiado: { en: "too much" },
  desde: { en: "since" },
  deseo: { en: "wish; desire" },
  despedirte: { en: "to say goodbye (to you)" },
  déjelo: { en: "leave it; let him be" },
  dicho: { en: "said" },
  dijo: { en: "said (he/she)" },
  don: { en: "Don (title)" },
  doncella: { en: "maid" },
  dote: { en: "dowry", pron: "DOH-teh" },
  dueñas: { en: "mistresses (of)" },
  egoísta: { en: "selfish" },
  el: { en: "the (m.)" },
  ella: { en: "she; it (f.)" },
  ellas: { en: "they (f.)" },
  empezará: { en: "will begin" },
  en: { en: "in; on" },
  encuentre: { en: "may (he) be; find (subj.)" },
  enviar: { en: "to send" },
  envió: { en: "sent" },
  es: { en: "is" },
  esa: { en: "that (f.)" },
  estas: { en: "these (f.)" },
  está: { en: "is; (location/state)" },
  esté: { en: "is (subj.)" },
  éste: { en: "this one" },
  ésta: { en: "this one (f.)" },
  excelente: { en: "excellent" },
  familiar: { en: "relative" },
  ganas: { en: "desire; urge" },
  gusta: { en: "pleases; like" },
  gusto: { en: "pleasure; taste" },
  ha: { en: "has (aux.)" },
  hace: { en: "makes; ago" },
  han: { en: "have (they)" },
  hasta: { en: "until; even" },
  hay: { en: "there is/are" },
  hayamos: { en: "we have (subj.)" },
  he: { en: "I have (aux.)" },
  hecha: { en: "made (f.)" },
  hecho: { en: "made; fact" },
  hermana: { en: "sister (nun)", pron: "air-MAH-nah" },
  hierbas: { en: "weeds; herbs" },
  hija: { en: "daughter" },
  hola: { en: "hello", pron: "OH-lah" },
  hoy: { en: "today" },
  humano: { en: "human" },
  importa: { en: "matters; cares" },
  importarte: { en: "to matter to you" },
  interesar: { en: "to interest" },
  interesaba: { en: "were interested" },
  invita: { en: "invites" },
  jaime: { en: "Jaime (name)" },
  jugar: { en: "to play" },
  la: { en: "the (f.); her; it" },
  las: { en: "the (f. pl.)" },
  le: { en: "to him/her" },
  les: { en: "to them" },
  llegó: { en: "arrived" },
  lo: { en: "it; him (neuter)" },
  los: { en: "the (m. pl.)" },
  lugar: { en: "place" },
  madre: { en: "mother", pron: "MAH-dreh" },
  mangos: { en: "handles" },
  mañana: { en: "morning; tomorrow", pron: "mah-NYAH-nah" },
  marcharte: { en: "to leave; go away" },
  material: { en: "material (things)" },
  más: { en: "more; most" },
  me: { en: "me; to me" },
  mejor: { en: "better; best" },
  mentir: { en: "to lie" },
  mi: { en: "my" },
  mismo: { en: "same" },
  modo: { en: "way; manner" },
  mucho: { en: "much; a lot" },
  muy: { en: "very" },
  ni: { en: "nor; not even" },
  ningún: { en: "no; not any" },
  ninguno: { en: "none" },
  no: { en: "no; not" },
  nos: { en: "us" },
  orden: { en: "order" },
  ordena: { en: "orders" },
  ordenar: { en: "to order" },
  ordenó: { en: "ordered" },
  pagado: { en: "paid" },
  para: { en: "for; to" },
  parece: { en: "it seems" },
  parezca: { en: "may seem" },
  pasa: { en: "happens; passes" },
  pedir: { en: "to ask for" },
  permiso: { en: "permission" },
  pero: { en: "but" },
  perrito: { en: "little dog; scamp" },
  pícara: { en: "rascal (f.)" },
  piso: { en: "floor (story)" },
  poco: { en: "little; few" },
  podrá: { en: "will be able" },
  puede: { en: "can; may" },
  por: { en: "for; by; through" },
  porque: { en: "because" },
  pues: { en: "well; since" },
  profesión: { en: "profession; vows ceremony" },
  profesar: { en: "to take vows" },
  pronto: { en: "soon" },
  procure: { en: "try to (formal imperative)" },
  qué: { en: "what; how" },
  que: { en: "that; which" },
  quedar: { en: "to stay; remain" },
  quedarme: { en: "to stay (myself)" },
  quedarte: { en: "to stay (yourself)" },
  quien: { en: "who" },
  quiere: { en: "wants" },
  quién: { en: "who?" },
  quieres: { en: "you want" },
  ramona: { en: "Ramona (name)" },
  razón: { en: "reason; right" },
  recibir: { en: "to receive" },
  regalado: { en: "given (as gift)" },
  reproducen: { en: "they reproduce" },
  respeto: { en: "respect" },
  retiro: { en: "retreat" },
  reverencia: { en: "reverend; Your Reverence" },
  rita: { en: "Rita (name)" },
  sal: { en: "get out" },
  salgo: { en: "I go out" },
  salir: { en: "to leave; go out" },
  salta: { en: "jumps" },
  saltar: { en: "to jump" },
  salvaje: { en: "wild" },
  se: { en: "himself; oneself; (passive)" },
  seguramente: { en: "surely" },
  señorita: { en: "miss; young lady" },
  ser: { en: "to be" },
  sería: { en: "would be" },
  si: { en: "if; whether" },
  siento: { en: "I feel; sorry" },
  sirvienta: { en: "maid" },
  soledad: { en: "loneliness; solitude" },
  solo: { en: "only; alone" },
  sólo: { en: "only" },
  sostenido: { en: "supported (past part.)" },
  soy: { en: "I am" },
  superiora: { en: "mother superior" },
  su: { en: "his; her; your (formal)" },
  sus: { en: "his/her/their" },
  tal: { en: "such" },
  también: { en: "also; too" },
  tampoco: { en: "neither; not … either" },
  tan: { en: "so" },
  tarde: { en: "late; afternoon" },
  te: { en: "you; to you" },
  temo: { en: "I fear" },
  tengo: { en: "I have" },
  tenido: { en: "had (part.)" },
  tiempo: { en: "time" },
  tiene: { en: "has" },
  tienes: { en: "you have" },
  tía: { en: "aunt" },
  tío: { en: "uncle", pron: "TEE-oh" },
  todo: { en: "all; everything" },
  toma: { en: "takes" },
  tomar: { en: "to take" },
  tomes: { en: "you take (subj.)" },
  trato: { en: "dealings; contact" },
  tranquilo: { en: "calm; quiet" },
  tu: { en: "your (fam.)" },
  tus: { en: "your (fam. pl.)" },
  tuvieron: { en: "they had to" },
  usted: { en: "you (formal)" },
  un: { en: "a; one" },
  una: { en: "a; one (f.)" },
  unos: { en: "some; a few" },
  único: { en: "only" },
  va: { en: "goes" },
  vas: { en: "you go" },
  vaya: { en: "go (subj.); may go" },
  ven: { en: "come" },
  venga: { en: "come on" },
  venir: { en: "to come" },
  ver: { en: "to see" },
  verdad: { en: "truth; right?" },
  verle: { en: "to see him" },
  verme: { en: "to see me" },
  vez: { en: "time (occasion)" },
  veces: { en: "times" },
  vete: { en: "go away" },
  vi: { en: "I saw" },
  viaje: { en: "journey; trip" },
  vine: { en: "I came" },
  viridiana: { en: "Viridiana (name)", pron: "vee-ree-DYAH-nah" },
  volver: { en: "to return" },
  volverás: { en: "you will return" },
  votos: { en: "vows" },
  voz: { en: "voice" },
  vuelto: { en: "become; returned (part.)" },
  y: { en: "and" },
  ya: { en: "already; now" },
  yo: { en: "I" },
};
